function dy = irSIR(~, y, params)

dy = [ ...
  -params.beta * y(1,:) .* y(2,:); ...
  params.beta * y(1,:) .* y(2,:) - params.nu * y(2,:) .* y(3,:); ...
  params.nu * y(2,:) .* y(3,:) ...
  ] .* params.N0;

end